title: Banana Translations
# tagline: Read free English fan translations of novels like Absolute Regression. No ads, no paywalls. Updated regularly.
baseurl: "" # the subpath of your site, e.g. /blog
repository: FeedFoodie/machinetranslations
url: "https://mtl.northbladetl.com" # the base hostname & protocol for your site, e.g. http://example.com
markdown: kramdown
markdown_ext: md
kramdown:  
  parse_block_html: true
  smart_quotes: ["apos", "apos", "quot", "quot"]
permalink: /:categories/:title:output_ext
logo: /android-chrome-512x512.png
pagination:
  enabled: true
  per_page: 20
  limit: 0
  sort_field: 'date'
  sort_reverse: true


# Build settings
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate-v2
