title: Banana Translations
tagline: BananaTL
description: We offer high-quality English fan translations of popular webnovels and novels like Absolute Regression.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://mtl.northbladetl.com" # the base hostname & protocol for your site, e.g. http://example.com
markdown: kramdown
markdown_ext: md
kramdown:  
  parse_block_html: true
  smart_quotes: ["apos", "apos", "quot", "quot"]
permalink: /:categories/:title:output_ext
logo: /android-chrome-512x512.png
pagination:
  enabled: true
  per_page: 20
  limit: 0
  sort_field: 'date'
  sort_reverse: true


# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate-v2
  
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
